/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.utils.*;
import org.example.service.*;

import java.util.Random;

import org.example.model.*;

public class EsportsManagmentApp {
    public static void main(String[] args) {

        // Inform the user that the tournament simulation is starting
        System.out.println("Starting The E-Sports Tournament Challenge...");

        Game[] allGames;
        Gamer[] allGamers;

        // Initialize file readers for games and gamers data
        GameFileIO gameReader = new GameFileIO("src/main/resources/games.csv");
        GamersFileIO gamerReader = new GamersFileIO("src/main/resources/gamers.csv");

        // Load all games and gamers from their respective CSV files
        allGames = gameReader.getGames();
        allGamers = gamerReader.getGamers();

        // Print statistics about loaded data
        System.out.println("Loaded " + allGamers.length + " gamers.");
        System.out.println("Loaded " + allGames.length + " games.");
        System.out.println("----------------------------------------");

        // Create a random number generator for match simulation
        Random random = new Random();

        // Initialize match management with loaded gamers and games
        MatchManagement matchManager = new MatchManagement(allGamers, allGames, random);

        // Generate matches for the tournament
        Match[][] allMatches = matchManager.getMatches();
        System.out.println("Simulation complete: " + (allGamers.length * 15) + " matches generated.");
        System.out.println("----------------------------------------");

        // Initialize the Query class for tournament statistics and queries
        Query query = new Query(allGamers, allMatches);

        // Print all requested queries/statistics
        query.printAllQueries();

        System.out.println("----------------------------------------");
        System.out.println("Tournament simulation finished.");

    }
}
